Desktop: add global shortcut to show/hide Joplin
laurent22/joplin pull request #2653
Opened 2020-03-04 00:38 UTC by tessus

Previously it was possible to open Joplin by clicking on the tray icon.
This functionality is no longer available due to changes in Electron.

The following key combination will show or hide Joplin in the current workspace:

- macOS: `Cmd+Opt+J`
- Linux, Windows: `Ctrl+Alt+J`

2020-03-15 12:02 UTC, laurent22 requested changes
Thanks @tessus, looks good overall. Could you also add a section in the README to document it? Maybe under the "Goto Anything" section.

2020-03-15 20:54 UTC, tessus commented on ElectronClient/ElectronAppWrapper.js
> +			console.log('Could not register global shortcut');
Sure. Done.

2020-03-15 20:55 UTC, tessus commented on ElectronClient/ElectronAppWrapper.js
> +		});
Yep, in a sec.

2020-03-15 20:59 UTC, tessus commented on ElectronClient/ElectronAppWrapper.js
> +		});
Done.

2020-03-15 21:42 UTC, tessus commented
All done.

Travis is failing due to linter errors in some other parts of the code:

```
/Users/travis/build/laurent22/joplin/CliClient/tests/integration_ShowAllNotes.js
   96:7  error  'folder1' is never reassigned. Use 'const' instead  prefer-const
   97:7  error  'folder2' is never reassigned. Use 'const' instead  prefer-const
   98:7  error  'note1' is never reassigned. Use 'const' instead    prefer-const
   99:7  error  'note2' is never reassigned. Use 'const' instead    prefer-const
  133:7  error  'folder1' is never reassigned. Use 'const' instead  prefer-const
  134:7  error  'folder2' is never reassigned. Use 'const' instead  prefer-const
  135:7  error  'note1' is never reassigned. Use 'const' instead    prefer-const
  136:7  error  'note2' is never reassigned. Use 'const' instead    prefer-const

/Users/travis/build/laurent22/joplin/CliClient/tests/models_BaseItem.js
  61:7  error  'folder' is never reassigned. Use 'const' instead        prefer-const
  62:7  error  'note' is never reassigned. Use 'const' instead          prefer-const
  64:7  error  'serialized' is never reassigned. Use 'const' instead    prefer-const
  65:7  error  'unserialized' is never reassigned. Use 'const' instead  prefer-const
```

2020-03-16 00:35 UTC, laurent22 commented
Great, thanks @tessus!

2020-03-16 00:36 UTC, merged

2020-03-23 08:54 UTC, hunhejj commented
It would be nice if it was possible to modify the global hotkey. On Hungarian keyboards `Ctrl+Alt+J` is actually a common letter (`í`)

2020-03-23 09:09 UTC, tessus commented
It will be part of the shortcut project for GSoC.

2020-03-23 09:21 UTC, hunhejj commented
Looking forward to GSoC! Reverting until then.

2020-03-24 14:45 UTC, tmerse commented
This should be made optional/configurable via config settings.
I cannot find a way in which a user can disable this, if it interferes with existing shortcuts.

2020-03-24 14:51 UTC, laurent22 commented
What should we do about this @tessus? The shortcut project is months away from being completed, and even if done there's no guarantee it will be merged.

Meanwhile, it's true that we're reserving a global shortcut that some users might need for other applications.

2020-03-24 19:49 UTC, tessus commented
3 options (all of which will be reverted as soon as we add the custom shortcut code):

- enable/disable global show/hide in settings
- `global.key` file in profile - very simple, just one entry, plain text
- remove it

2020-03-29 22:56 UTC, tessus commented
What shall I do?

2020-03-30 13:57 UTC, coderrsid commented
I think for now we should change the shortcut to something less common than `Cmd+opt+J` `Ctrl+Alt+J` until the custom keyboard shortcut project is done?

2020-03-30 14:00 UTC, laurent22 commented
Without a way to customise the shortcut I think this feature is too incomplete, but we have nothing for customisation yet. So for now I think it should be removed, and we can put it back once the shortcut project is completed.

2020-03-30 14:14 UTC, tessus commented
In that case we can just revert the commit.

2020-04-05 21:29 UTC, tessus commented
@laurent22 shall I revert the commit? create a PR? revert and push directly on master?

2020-04-15 08:57 UTC, laurent22 commented
Yes please, for now revert and push directly to master.

2020-04-15 15:45 UTC, R-L-T-Y commented
Maybe if can take arguments like `joplin-desktop toggle` and people can bind easily on windows, various WM of linux and macOS.

2021-01-13 15:14 UTC, domi0003 commented
Tried to find this functionality in current version 1.6.7 and was not able to find it. Is it planned to be included in the future?

2021-03-14 10:46 UTC, uditarenos commented
Still the same in 1.7.11.

Is there any chance to open (& close to tray) joplin by right-clicking on the tray icon? At the moment, a menu appears (1. open joplin; 2. quit Joplin).

2021-03-14 11:33 UTC, tessus commented
We don't have global shortcuts in the shortcut editor, which means we had to revert the change, because some people already used that shortcut for something else.
I would have said, who cares, let others fix their shortcuts, but it wasn't my decision.

2022-10-23 11:49 UTC, awayand commented
is this initiative dead? would love to have a global hotkey to activate joplin

2022-10-23 19:13 UTC, tessus commented
@awayand I mentioned this a few times on the forum and wanted to get this rolling again, but I guess it was at a time where there were more important problems to tackle.

But I use this shortcut in my personal build. I think it would be nice to have other global shortcuts, like one for creating a new note (and show Joplin when hidden).

The problem with this PR was that the shortcut conflicted with a Linux shortcut. I didn't understand why that should be Joplin's problem, since other apps don't care either and it's possible to change the Linux shortcut in Linux. But this was the reason why it was reverted a short while after.

I haven't looked at the shortcut editor code for a while, but we would have to create a seprate section on that screen for global shortcuts. It's also necessary to treat them differently, because they are initialized in a different area of the code.

Maybe you can bring this up on the forum again. It's possible that someone has the time to implement it. I can't code this myself at the moment, but I can help and acts as a mentor.

2023-01-04 10:56 UTC, mullimanko commented
Here is a workaround for Microsoft Windows users.
AutoHotkey (an automation app) allows to interact with the system tray icon of Joplin. Determine your desired keyboard shortcut (also called hotkey) to execute the command of bringing Joplin at focus or rather to the foreground (here the desired keyboard shortcut is: Ctrl + Alt + k (Ctrl is represented by ^; Alt is represented by !; k is represented by k). The following code in an AutoHotkey file would what is requested here:

```
DetectHiddenWindows, On
CoordMode, Mouse, Screen

; This code automates opening Joplin from the system tray menu.
; This code is designed this way because it's fastest and most reliable 
; in the context of the Joplin app if you have only one app icon 
; starting with "J" in the system tray menu.
^!k::
WinSet, Transparent, 1, % winTitle := "ahk_class NotifyIconOverflowWindow"
WinShow, % winTitle
WinActivate, % winTitle
ControlFocus, ToolbarWindow321, % winTitle
MouseGetPos, xpos, ypos
Send, j{Enter}  ; This selects and starts Joplin because it begins with a "J".
MouseMove, xpos, ypos, 0
WinHide, % winTitle
WinSet, Transparent, Off, % winTitle
Return
```
If you have another app icon, which name begins with "J" besides Joplin in the system tray menu you probably need to include `{LEFT}` straight before `{Enter}`, i.e. the whole line would be `Send, j{LEFT}{Enter}`. However, in the most cases Joplin is the only app beginning with J in the system tray menu.

A short video how to install AutoHotkey and create and use a first AutoHotkey file (.ahk file) can be found on youtube: https://www.youtube.com/watch?v=k7e9MrP-U_g

2023-01-05 11:58 UTC, xaa commented
(Windows user could just pin the app on the taskbar then press win+1 to open/reduce Joplin (number 1 = the icon position on the taskbar)

2023-01-06 13:46 UTC, mullimanko commented
Yeah, but the opening post suggested the hotkey `Ctrl+Alt+J` (which can be achieved with `^!k::` in the above code), your solution is less flexible (Windows button + number).

2025-02-08 00:02 UTC, laurent22 commented
Now that we have support for shortcuts and commands we could probably add this feature