Update French translation + fix a typo
laurent22/joplin pull request #4349
Opened 2021-01-12 10:46 UTC by jibedoubleve

Fix a typo and add the missing translation.

2021-01-12 13:45 UTC, laurent22 requested changes

2021-01-12 13:45 UTC, laurent22 commented on packages/tools/locales/fr_FR.po
> +"Le mot de passe admin par défaut n’est pas sûr et n’a pas été modifié! "
Il faut un espace avant le point d'exclamation.

2021-01-12 13:45 UTC, laurent22 commented on packages/tools/locales/fr_FR.po
> +"[Changez-le maintenant] (%s)"
Pas d'espace entre ] et (

2021-01-12 13:45 UTC, laurent22 commented on packages/tools/locales/fr_FR.po
> +"Le mot de passe admin par défaut n’est pas sûr et n’a pas été modifié! "
`’` => `'`

"n'est pas sûr" => "n'est pas sécurisé"

2021-01-13 08:40 UTC, jibedoubleve commented on packages/tools/locales/fr_FR.po
> +"[Changez-le maintenant] (%s)"
J'ai fait les corrections.

2021-01-13 08:45 UTC, jibedoubleve commented on packages/tools/locales/fr_FR.po
> +"Le mot de passe admin par défaut n’est pas sûr et n’a pas été modifié! "
J'ai fait les corrections.

2021-01-13 12:39 UTC, laurent22 commented
Merci pour la mise-à-jour !

2021-01-13 12:39 UTC, merged