Update mobile.md
laurent22/joplin pull request #5252
Opened 2021-07-30 12:14 UTC by abhi-bhatra

Mobile: Add mobile interface Infographic in Readme File

Explanation: 
I am using Joplin from a very long time. I visited the Joplin Repo, and I found that Desktop Application Infographic is available which helps user in Navigating the Desktop Application. But, There is no such useful Infographic for Mobile interface.
I created an infographic for Mobile Application, which might help the users a lot.

2021-08-04 10:11 UTC, abhi-bhatra commented
@laurent22 I have added the Mobile UI Infographics to readme/mobile.md which enhances the user experience documentation.
Take a look: 
https://user-images.githubusercontent.com/63901956/127650128-2e00a545-1973-45ed-8442-74f8fc39277e.png

2021-08-04 19:36 UTC, tessus commented
afaik graphics should be local to the files and not loaded from external sources.
Let's see what Laurent says...

2021-08-04 19:48 UTC, abhi-bhatra commented
Hi
The graphic is created by me itself. It is not loaded from any external resources. I have been using joplin, and its just my own user experience I have shared.

2021-08-04 20:17 UTC, tessus commented
I think youu misunderstood. Put the image in the PR. (Check how other images are used in the md files.)

2021-08-04 21:46 UTC, laurent22 commented
Indeed thank you for the image, I think it's useful, but it needs to be part of the repository. Also please convert it to a JPEG at 90% quality (should result in a much smaller file, but still good quality).

2021-08-05 03:42 UTC, abhi-bhatra commented
Thanks @laurent22 and @tessus
I got your point and applied the necessary changes

2021-08-05 11:05 UTC, tessus requested changes

2021-08-05 11:05 UTC, tessus commented on readme/mobile.md
> +<img src="https://github.com/abhi-bhatra/joplin/blob/patch-3/Assets/JoplinMobileui.jpg" style="max-width=100%"/>
You are still pointing to your repository.

2021-08-05 11:16 UTC, tessus commented on readme/mobile.md
> +<img src="https://github.com/abhi-bhatra/joplin/blob/patch-3/Assets/JoplinMobileui.jpg" style="max-width=100%"/>
And the file should be renamed to `JoplinMobileUI.jpg` and placed in `Assets/WebsiteAssets/images/`.

2021-08-05 11:19 UTC, tessus commented
I mentioned you should check how other images are included. When you check the readme or other md files, including an image usually looks like this:

```
![](https://joplinapp.org/images/imagename.jpg)
```

2021-08-05 11:21 UTC, tessus commented
Are vyou sure you saved the image as 90% quality jph. It still seems rather large.

2021-08-05 11:52 UTC, abhi-bhatra commented
@tessus Yes I have saved the image with 90% quality. Do, I keep it more small ?

2021-08-05 12:07 UTC, tessus commented
> Yes I have saved the image with 90% quality. Do, I keep it more small ?

1.14MB seems a bit large for a few lines and very few colors, but if it's been saved as 90%, it should be ok. 

> I have also changed the image link to laurent22:dev . Kindly review and please guide me on the same!

I'm not sure about this part, since it's a bit inconsistent in the readme and other md files.
@laurent22 shall we keep it as is `<img src="https://github.com/laurent22/joplin/tree/dev/Assets/WebsiteAssets/images/JoplinMobileUI.jpg" style="max-width=100%"/>` or change it to `![](https://joplinapp.org/images/JoplinMobileUI.jpg)`

2021-08-05 12:35 UTC, abhi-bhatra commented
@tessus The pull have been disabled to the main `laurent:dev` so I am refering to this `https://github.com/laurent22/joplin/tree/dev/Assets/WebsiteAssets/images/JoplinMobileUI.jpg` and when pull request is merged, it will be address correctly. @laurent22 please guide me on the same!

2021-08-05 13:17 UTC, tessus commented
I think you still don't understand what I was saying. If you had looked at the md files, you would have realized that there are 2 options, namely the ones I mentioned above.

Please don't mention us. We get notifications anyway. I only mentioned Laurent to indicate that we can merge as soon as he makes his decision.

2021-08-05 13:22 UTC, laurent22 commented
For the image, please use the attached one as it's better compressed.

![DemoMobile](https://user-images.githubusercontent.com/1285584/128356761-68252b8e-8ea4-442b-87ca-c98595170174.jpg)

Link should be like in desktop.md - `<img src="https://joplinapp.org/images/DemoMobile.jpg" style="max-width: 100%">`

And the image should go in docs/images

2021-08-05 13:25 UTC, tessus commented
> And the image should go in docs/images

Yep, sorry, my bad. I mixed up the dirs.

2021-08-05 14:24 UTC, abhi-bhatra commented
> And the image should go in docs/images

Thank you @laurent22 that is why I am confused with how to link the image like this one : `https://joplinapp.org/images/DemoMobile.jpg`
I will do the necessary changes now
Thanks to @tessus too ❤

2021-08-05 22:16 UTC, tessus commented
Thanks for the changes.

2021-08-05 22:18 UTC, merged