fix package name in readme
laurent22/joplin pull request #9674
Opened 2024-01-06 16:12 UTC by awxiaoxian2020

2024-01-06 16:18 UTC, awxiaoxian2020 commented
I have read the CLA Document and I hereby sign the CLA

2024-01-06 16:18 UTC, awxiaoxian2020 commented
recheck

2024-01-06 16:26 UTC, personalizedrefrigerator requested changes
Thank you for the fix!

Be aware that we have a [script that automatically generates release notes from commit titles](https://github.com/laurent22/joplin/blob/f8a25cb275a0beb9ba3ef9bf4271d38947449f42/packages/tools/git-changelog.ts#L358). As such, a better name for this pull request might be `Chore: turndown-plugin-gfm: Fix package name in README` (the `Chore:` part prevents it from showing up in Joplin's release notes).

2024-01-06 16:26 UTC, personalizedrefrigerator commented on packages/turndown-plugin-gfm/README.md
> +var tables = require('joplin-turndown-plugin-gfm').tables
```suggestion
var tables = require('@joplin/turndown-plugin-gfm').tables
```

See https://github.com/laurent22/joplin/blob/dev/packages/turndown-plugin-gfm/package.json#L2C12-L2C20

2024-01-07 02:59 UTC, awxiaoxian2020 commented
> Thank you for the fix!
> 
> Be aware that we have a [script that automatically generates release notes from commit titles](https://github.com/laurent22/joplin/blob/f8a25cb275a0beb9ba3ef9bf4271d38947449f42/packages/tools/git-changelog.ts#L358). As such, a better name for this pull request might be `Chore: turndown-plugin-gfm: Fix package name in README` (the `Chore:` part prevents it from showing up in Joplin's release notes).

Could you update the contributing guide to give a tip for other contributors? :)

2024-01-08 11:55 UTC, laurent22 commented
> Could you update the contributing guide to give a tip for other contributors? :)

It's all in the pull request description, when you create it:

> Please prefix the title with the platform you are targetting:
> 
> Here are some examples of good titles:
> 
> - Desktop: Resolves #123: Added new setting to change font
> - Mobile, Desktop: Fixes #456: Fixed config screen error
> - All: Resolves #777: Made synchronisation faster
> 
> And here's an explanation of the title format:
> 
> - "Desktop" for the Windows/macOS/Linux app (Electron app)
> - "Mobile" for the mobile app (or "Android" / "iOS" if the pull request only applies to one of the mobile platforms)
> - "CLI" for the CLI app
> 
> If it's two platforms, separate them with commas - "Desktop, Mobile" or if it's for all platforms, prefix with "All".
> 
> If it's not related to any platform (such as a translation, change to the documentation, etc.), simply don't add a platform.
> 
> Then please append the issue that you've addressed or fixed. Use "Resolves #123" for new features or improvements and "Fixes #123" for > bug fixes.
> 
> AND PLEASE READ THE GUIDE: https://github.com/laurent22/joplin/blob/dev/CONTRIBUTING.md

2024-01-08 11:56 UTC, merged

2024-01-08 11:56 UTC, laurent22 commented
Thanks for the fix!