CLI: Added option to show full id in ls command
laurent22/joplin pull request #9936
Opened 2024-02-14 12:21 UTC by RenatoXSR

As the ls command only shjows either the title, or the title, short id and date, there is no way to programatically obtain the necessary id to create a joplin internal URL in scripts.

Added the -i --id option to the ls command, which, by itself, shows the full id in parenthesis after the title, or if combined with the -l --long option, it just shows the full id, so scripts can extract them and create valid internal links (:/[id]).

--

Renato.

2024-02-14 14:34 UTC, personalizedrefrigerator requested changes
Thank you for the pull request!

> As the ls command only shjows either the title, or the title, short id and date, there is no way to programatically obtain the necessary id to create a joplin internal URL in scripts.

Consider using the `--format json` option instead. It should provide the full ID in addition to other information. For example, `joplin-cli ls --format json`.

2024-02-14 14:34 UTC, personalizedrefrigerator commented on packages/app-cli/app/command-ls.ts
> +			['-i, --id', _('Show full ID of items."')],
```suggestion
			['--always-show-full-id', _('Always show full IDs of items.')],
```

In some cases, the full ID of an item can still be shown, even if this option isn't provided. As such, a more descriptive option name could be helpful.

2024-02-14 14:34 UTC, personalizedrefrigerator commented on packages/app-cli/app/command-ls.ts
> +					options.id ? row.push(item.id) : row.push(BaseModel.shortId(item.id));
```suggestion
					row.push(options.id ? item.id : BaseModel.shortId(item.id));
```

2024-02-14 14:34 UTC, personalizedrefrigerator commented on packages/app-cli/app/command-ls.ts
>  					shortIdShown = true;
Consider renaming `shortIdShown`, as this name is no longer accurate.

2024-02-14 14:34 UTC, personalizedrefrigerator commented on packages/app-cli/app/command-ls.ts
> +					options.id ? title += ` (${item.id})` : title += ` (${BaseModel.shortId(item.id)})`;
```suggestion
					title += options.id ? ` (${item.id})` : (${BaseModel.shortId(item.id)})`;
```

2024-02-19 10:06 UTC, laurent22 commented
@RenatoXSR, please could you sign the CLA so that we can proceed with this pull request?

2024-02-22 15:39 UTC, laurent22 commented
@RenatoXSR, we try not to keep too many PRs open so please let us know when you'll have time to look into the issues mentioned in review, and we'll reopen the pull request

2024-02-22 15:39 UTC, closed without merging